project:
  type: website

website:
  title: "Pristine Seas Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Methods
      - href: index.qmd
        text: Expeditions
      - href: index.qmd
        text: Publications
      - href: index.qmd
        text: Meet the team
      - text: "Posts"
        menu: 
          - text: "PS Dropcams"
            href: dscm.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

